### ISSUE TITLE
`sr` and `sr-ec` are not in Latin script

### ISSUE THREAD

**Issue by zenfiric** [dereckson/Daeghrefn-Wikidata#5]
Serbian, and especially `sr-ec` should not be on the `latin-whitelist.json`.

**Comment by dereckson** [comment]
Task discussed on https://devcentral.nasqueron.org/T1238

**Code review:** https://devcentral.nasqueron.org/D1022

**Comment by dereckson** [comment]
Fixed by abd56e0d6 for `sr-ec`.

So, for `sr`, perhaps that should be discussed on Wikidata what alphabet or alphabets this code should receive.
